- name: Check Docker service status
  hosts: all
  become: yes
  tasks:
    - name: Check if Docker service is running
      block:
        - name: Run systemctl status docker
          command: systemctl status docker
          register: docker_status
          ignore_errors: true

        - name: Print Docker service status
          debug:
            msg: "Docker service status on {{ inventory_hostname }}: {{ docker_status.stdout }}"
          when: docker_status is succeeded

      rescue:
        - name: Print error message if Docker service not found
          debug:
            msg: "Docker service not found on {{ inventory_hostname }}"
          when: docker_status.rc == 4

        - name: Print error message if Docker service inactive
          debug:
            msg: "Docker service inactive on {{ inventory_hostname }}"
          when: docker_status.rc == 3

        - name: Print error message if unable to run systemctl
          debug:
            msg: "Unable to run systemctl on {{ inventory_hostname }}"
          when: docker_status is failed
