- name: Remove Docker from all hosts
  hosts: all
  become: yes
  tasks:
    - name: Stop Docker service
      service:
        name: docker
        state: stopped
      ignore_errors: yes

    - name: Remove Docker package on Ubuntu
      apt:
        name: docker-ce
        state: absent
      when: ansible_distribution == 'Ubuntu' and ansible_pkg_mgr == 'apt'

    - name: Remove Docker directory on Ubuntu
      file:
        path: "/var/lib/docker"
        state: absent
      when: ansible_distribution == 'Ubuntu' and ansible_pkg_mgr == 'apt'

    - name: Remove Docker package on CentOS
      yum:
        name: docker-ce
        state: absent
      when: ansible_distribution == 'CentOS' and ansible_pkg_mgr == 'yum'

    - name: Remove Docker directory on CentOS
      file:
        path: "/var/lib/docker"
        state: absent
      when: ansible_distribution == 'CentOS' and ansible_pkg_mgr == 'yum'

